// <auto-generated />
using System;
using CommunicatieAppBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunicatieAppBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230217091632_newmig")]
    partial class newmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CommunicatieAppBackend.Models.Melding", b =>
                {
                    b.Property<int>("MeldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Inhoud")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MeldingId");

                    b.ToTable("meldingen");

                    b.HasData(
                        new
                        {
                            MeldingId = 1,
                            Datum = new DateTime(2023, 2, 17, 10, 16, 32, 589, DateTimeKind.Local).AddTicks(8546),
                            Inhoud = "hoi",
                            Titel = "test"
                        },
                        new
                        {
                            MeldingId = 2,
                            Datum = new DateTime(2023, 2, 17, 10, 16, 32, 589, DateTimeKind.Local).AddTicks(8612),
                            Inhoud = "hoi2",
                            Titel = "test2"
                        });
                });

            modelBuilder.Entity("CommunicatieAppBackend.Models.Nieuwsbericht", b =>
                {
                    b.Property<int>("NieuwsberichtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Inhoud")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NieuwsberichtId");

                    b.ToTable("nieuwsberichten");

                    b.HasData(
                        new
                        {
                            NieuwsberichtId = 1,
                            Datum = new DateTime(2023, 2, 17, 10, 16, 32, 589, DateTimeKind.Local).AddTicks(8827),
                            Image = "noimage",
                            Inhoud = "hoi",
                            Titel = "test"
                        },
                        new
                        {
                            NieuwsberichtId = 2,
                            Datum = new DateTime(2023, 2, 17, 10, 16, 32, 589, DateTimeKind.Local).AddTicks(8837),
                            Image = "noimage",
                            Inhoud = "hoi2",
                            Titel = "test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
